"""add admin table

Revision ID: 03098b0b6326
Revises: 9925b4bde808
Create Date: 2025-10-13 17:12:21.855858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03098b0b6326'
down_revision = '9925b4bde808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('full_price',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('full_price',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
