"""Add icon column to categories table

Revision ID: 52320ff0eb22
Revises: e2ec0c0b7770
Create Date: 2025-10-09 21:17:00.152164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52320ff0eb22'
down_revision = 'e2ec0c0b7770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
